[package]
name = "sha-crypt"
version = "0.4.0"
description = """
Pure Rust implementation of the SHA-crypt password hash based on SHA-512
as implemented by the POSIX crypt C library
"""
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/sha-crypt"
repository = "https://github.com/RustCrypto/password-hashes/tree/master/sha-crypt"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "password", "hashing"]
readme = "README.md"
edition = "2021"
rust-version = "1.56"

[dependencies]
sha2 = { version = "0.10", default-features = false }

# optional dependencies
rand = { version = "0.8", optional = true }
subtle = { version = ">=2, <2.5", optional = true, default-features = false }
base64ct = { git = "https://github.com/ibotty/rustcrypto-formats", rev = "c0df69f7028cba1016018d7a57a89fb95cd22f83" }

[features]
default = ["simple"]
simple = ["rand", "std", "subtle"]
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
