[package]
name = "password-auth"
version = "0.1.1"
description = """
Password authentication library with a focus on simplicity and ease-of-use,
with support for Argon2, PBKDF2, and scrypt password hashing algorithms
"""
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/password-auth"
repository = "https://github.com/RustCrypto/password-hashes/tree/master/password-auth"
keywords = ["crypto", "password", "hashing"]
categories = ["authentication", "cryptography", "no-std"]
readme = "README.md"
edition = "2021"
rust-version = "1.65"

[dependencies]
password-hash = { version = "0.5", features = ["alloc", "rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }

# optional dependencies
argon2 = { version = "0.5", optional = true, default-features = false, features = ["alloc", "simple"], path = "../argon2" }
pbkdf2 = { version = "0.12", optional = true, default-features = false, features = ["simple"], path = "../pbkdf2" }
scrypt =  { version = "0.11", optional = true, default-features = false, features = ["simple"], path = "../scrypt" }

[features]
default = ["argon2", "std"]
std = []

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
